### ISSUE TITLE
doc build failing?

### ISSUE THREAD

**Issue by jack-h** [casper-astro/tutorials_devel#82]
`https://tutorials-devel.readthedocs.io` seems mangled.... :grimacing:

**Comment by jkocz** [comment]
Just went over this with @mitchburnett . I don't think this is an "offical" page? 

The tutorials_devel repository is at: https://casper-toolflow.readthedocs.io/projects/tutorials/en/latest/

https://tutorials-devel.readthedocs.io is linked to a private account, not casper-astro. (So in short, I don't think we can fix this).

**Comment by jack-h** [comment]
Well I never! 

Ok, probably the docs-build badge and link on the repo landing page should be changed. 

I'll try to fix

**Comment by jkocz** [comment]
That said, there _is_ currently an issue with the tutorials devel build (we haven't actually updated, so the old build is fine, but the current regen issue is: 
""
Sphinx version error:
The alabaster extension used by this project needs at least Sphinx v3.4; it therefore cannot be built with this version.
""

It might be as simple as updating the versions of things in the config file?

**Comment by jack-h** [comment]
Ah, I see the badge does actually link the right place.

The `About` section of the landing page linked the wrong place, so I fixed that.

**Comment by jkocz** [comment]
I made some changes that allow the build to happen again (updated versions in requirements.txt and fixed associated bugs), however, the build is still not quite working, as it seems we have quite a mix of .rst and .md, and that's now causing us some issues: 
e.g. tutorials_devel/docs/index.rst:82: WARNING: toctree contains reference to document 'tutorials/snap/tut_intro' that doesn't have a title: no link will be generated

this error apparently occurs when there is no title in the associated file (in this case, tut_intro). However, tut_intro does have a title, it's just in md format and not .rst.

**Comment by jkocz** [comment]
Fixed by using "m2r" to convert all of the .md files to .rst format.
